CREATE TABLE STUDENTS(
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(100) NOT NULL,
    STUDENT_EMAIL VARCHAR(150) NOT NULL UNIQUE,
    STUDENT_PHONE VARCHAR(15) NOT NULL UNIQUE,
    STUDNET_ADDRESS VARCHAR(300) NOT NULL,
    STUDENT_DOB DATE NOT NULL,
    STUDENT_GENDER VARCHAR(20) NOT NULL,
    STUDENT_AGE INT NOT NULL,
    STUDENT_COURSE VARCHAR(100) NOT NULL,
    STUDENT_MAJOR VARCHAR(100) NOT NULL,
);
INSERT INTO STUDENTS(STUDENT_ID, STUDENT_NAME, STUDENT_EMAIL, STUDENT_PHONE, STUDNET_ADDRESS, STUDENT_DOB,
                    STUDENT_GENDER, STUDENT_AGE, STUDENT_COURSE, STUDENT_MAJOR    
                )
VALUES(1234, "John", "John@email.com", "12345", "123 street, city, country", "2000-01-01", "Male", 34, "Data Science", "Computer Science")
,(1235, "Boby", "boby@email.com", "12346", "124 street, city, country", "2001-01-01", "Male", 26, "Cyber Security", "Computer Science")
,(1236, "Tina", "Tina@email.com", "12347", "125 street, city, country", "1999-01-01", "Female", 28, "Dev-Ops", "Computer Science");

SELECT STUDENT_DOB FROM STUDENTS;